// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuspensionDesigner.Infrastructure.Data;

#nullable disable

namespace SuspensionDesigner.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260309172715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuspensionDesigner.Core.Entities.SuspensionDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AxlePosition")
                        .HasColumnType("integer");

                    b.Property<double>("CgHeight")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DampingCoefficient")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("FrontBrakeProportion")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("RideHeight")
                        .HasColumnType("double precision");

                    b.Property<double>("SpringRate")
                        .HasColumnType("double precision");

                    b.Property<double>("SprungMass")
                        .HasColumnType("double precision");

                    b.Property<int>("SuspensionType")
                        .HasColumnType("integer");

                    b.Property<double>("TireRadius")
                        .HasColumnType("double precision");

                    b.Property<double>("TrackWidth")
                        .HasColumnType("double precision");

                    b.Property<double>("UnsprungMass")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<double>("Wheelbase")
                        .HasColumnType("double precision");

                    b.ComplexProperty<Dictionary<string, object>>("LowerBallJoint", "SuspensionDesigner.Core.Entities.SuspensionDesign.LowerBallJoint#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerBallJoint_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerBallJoint_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerBallJoint_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LowerWishboneFrontPivot", "SuspensionDesigner.Core.Entities.SuspensionDesign.LowerWishboneFrontPivot#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerWishboneFrontPivot_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerWishboneFrontPivot_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerWishboneFrontPivot_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LowerWishboneRearPivot", "SuspensionDesigner.Core.Entities.SuspensionDesign.LowerWishboneRearPivot#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerWishboneRearPivot_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerWishboneRearPivot_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("LowerWishboneRearPivot_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PushrodRockerEnd", "SuspensionDesigner.Core.Entities.SuspensionDesign.PushrodRockerEnd#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("PushrodRockerEnd_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("PushrodRockerEnd_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("PushrodRockerEnd_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PushrodWheelEnd", "SuspensionDesigner.Core.Entities.SuspensionDesign.PushrodWheelEnd#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("PushrodWheelEnd_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("PushrodWheelEnd_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("PushrodWheelEnd_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SpringDamperLower", "SuspensionDesigner.Core.Entities.SuspensionDesign.SpringDamperLower#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("SpringDamperLower_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("SpringDamperLower_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("SpringDamperLower_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SpringDamperUpper", "SuspensionDesigner.Core.Entities.SuspensionDesign.SpringDamperUpper#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("SpringDamperUpper_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("SpringDamperUpper_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("SpringDamperUpper_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TieRodInner", "SuspensionDesigner.Core.Entities.SuspensionDesign.TieRodInner#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("TieRodInner_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("TieRodInner_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("TieRodInner_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TieRodOuter", "SuspensionDesigner.Core.Entities.SuspensionDesign.TieRodOuter#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("TieRodOuter_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("TieRodOuter_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("TieRodOuter_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UpperBallJoint", "SuspensionDesigner.Core.Entities.SuspensionDesign.UpperBallJoint#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperBallJoint_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperBallJoint_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperBallJoint_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UpperWishboneFrontPivot", "SuspensionDesigner.Core.Entities.SuspensionDesign.UpperWishboneFrontPivot#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperWishboneFrontPivot_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperWishboneFrontPivot_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperWishboneFrontPivot_Z");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UpperWishboneRearPivot", "SuspensionDesigner.Core.Entities.SuspensionDesign.UpperWishboneRearPivot#Point3D", b1 =>
                        {
                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperWishboneRearPivot_X");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperWishboneRearPivot_Y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("UpperWishboneRearPivot_Z");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SuspensionDesigns");
                });

            modelBuilder.Entity("SuspensionDesigner.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
